name: Upload python tool cache
on: push

jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: app

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      #- name: Set pip mirror
      #  run: |
      #    pip3 config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

      - name: Install cmake tools
        run: |
          pip3 install cmake

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build
        run: |
          west build app
